### DISCUSSION TITLE
Hiding and showing elements based on material 3 size guidelines

### DISCUSSION THREAD

**Discussion by treeder** [treeder/material#14] [General]
Here's a helpful CSS snippet you can use:

```css
@media (width < 600px) {
    :is(.medium, .expanded):not(.compact) {
        display: none;
    }
}
@media (width >= 600px) and (width < 840px) {
    :is(.compact, .expanded):not(.medium) {
        display: none;
    }
}

@media (width >= 840px) {
    :is(.compact, .medium):not(.expanded) {
        display: none;
    }
}
```
